Onegin.exe: Unit_tests.o Onegin_Main.o Working_with_array.o Strings_Sorting.o
	g++ Unit_tests.o Onegin_Main.o Working_with_array.o Strings_Sorting.o -o Onegin.exe

Unit_test.o: Unit_tests.cpp
	g++ -c Unit_tests.o

Onegin_Main.o: Onegin_Main.cpp
	g++ -c Onegin_Main.cpp

Working_with_array.o: Working_with_array.cpp
	g++ -c Working_with_array.cpp

Strings_Sorting.o: Strings_Sorting.cpp
	g++ -c Strings_Sorting.cpp